
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author asus
 */
public class Tugas3_1 extends javax.swing.JFrame {

    /**
     * Creates new form Tugas3_1
     */
    public Tugas3_1() {
        initComponents();
    }

    public void setImage(String Gambar, JLabel Label, int width, int height){
        ImageIcon Cover = new ImageIcon(getClass().getResource(Gambar));
        Image cover = Cover.getImage().getScaledInstance(width, height, Image.SCALE_SMOOTH ); 
        Label.setIcon(new ImageIcon(cover));}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pDaftar = new javax.swing.JPanel();
        lbDaftar = new javax.swing.JLabel();
        btJurus = new javax.swing.JButton();
        btSigarlaki = new javax.swing.JButton();
        btFabel = new javax.swing.JButton();
        btNina = new javax.swing.JButton();
        btBin = new javax.swing.JButton();
        btTuhan = new javax.swing.JButton();
        pDetailBuku = new javax.swing.JPanel();
        pCover = new javax.swing.JPanel();
        pDepan = new javax.swing.JPanel();
        lbDepan = new javax.swing.JLabel();
        pBelakang = new javax.swing.JPanel();
        lbBelakang = new javax.swing.JLabel();
        pDetail = new javax.swing.JPanel();
        lbJudul = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        lbPenulis = new javax.swing.JLabel();
        lbPenerbit = new javax.swing.JLabel();
        lbTerbit = new javax.swing.JLabel();
        lbHalaman = new javax.swing.JLabel();
        tfPenulis = new javax.swing.JTextField();
        tfPenerbit = new javax.swing.JTextField();
        tfTahun = new javax.swing.JTextField();
        tfHalaman = new javax.swing.JTextField();
        pJudul = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        pDaftar.setBackground(new java.awt.Color(153, 153, 255));
        pDaftar.setLayout(new java.awt.GridLayout(7, 0, 0, 3));

        lbDaftar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbDaftar.setForeground(new java.awt.Color(0, 0, 102));
        lbDaftar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbDaftar.setText("DAFTAR BUKU");
        pDaftar.add(lbDaftar);

        btJurus.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btJurus.setForeground(new java.awt.Color(51, 51, 51));
        btJurus.setText("19 JURUS");
        btJurus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btJurusActionPerformed(evt);
            }
        });
        pDaftar.add(btJurus);

        btSigarlaki.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btSigarlaki.setForeground(new java.awt.Color(51, 51, 51));
        btSigarlaki.setText("SIGARLAKI");
        btSigarlaki.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSigarlakiActionPerformed(evt);
            }
        });
        pDaftar.add(btSigarlaki);

        btFabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btFabel.setForeground(new java.awt.Color(51, 51, 51));
        btFabel.setText("FABEL ABC");
        btFabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFabelActionPerformed(evt);
            }
        });
        pDaftar.add(btFabel);

        btNina.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btNina.setForeground(new java.awt.Color(51, 51, 51));
        btNina.setText("NinaBobo");
        btNina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNinaActionPerformed(evt);
            }
        });
        pDaftar.add(btNina);

        btBin.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btBin.setForeground(new java.awt.Color(51, 51, 51));
        btBin.setText("BIN & TIM");
        btBin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBinActionPerformed(evt);
            }
        });
        pDaftar.add(btBin);

        btTuhan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btTuhan.setForeground(new java.awt.Color(51, 51, 51));
        btTuhan.setText("TUHAN");
        btTuhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTuhanActionPerformed(evt);
            }
        });
        pDaftar.add(btTuhan);

        getContentPane().add(pDaftar);
        pDaftar.setBounds(0, 96, 160, 370);

        pDetailBuku.setBackground(new java.awt.Color(204, 204, 255));
        pDetailBuku.setLayout(null);

        pCover.setBackground(new java.awt.Color(204, 153, 255));
        pCover.setLayout(new java.awt.GridLayout(2, 0));

        pDepan.setBackground(new java.awt.Color(255, 255, 255));

        lbDepan.setBackground(new java.awt.Color(204, 204, 255));
        lbDepan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbDepan.setForeground(new java.awt.Color(153, 153, 153));
        lbDepan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbDepan.setText("COVER DEPAN");
        lbDepan.setToolTipText("");

        javax.swing.GroupLayout pDepanLayout = new javax.swing.GroupLayout(pDepan);
        pDepan.setLayout(pDepanLayout);
        pDepanLayout.setHorizontalGroup(
            pDepanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pDepanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbDepan, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                .addContainerGap())
        );
        pDepanLayout.setVerticalGroup(
            pDepanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pDepanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbDepan, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                .addContainerGap())
        );

        pCover.add(pDepan);

        pBelakang.setBackground(new java.awt.Color(255, 255, 255));

        lbBelakang.setBackground(new java.awt.Color(255, 255, 255));
        lbBelakang.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbBelakang.setForeground(new java.awt.Color(153, 153, 153));
        lbBelakang.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbBelakang.setText("COVER BELAKANG");

        javax.swing.GroupLayout pBelakangLayout = new javax.swing.GroupLayout(pBelakang);
        pBelakang.setLayout(pBelakangLayout);
        pBelakangLayout.setHorizontalGroup(
            pBelakangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pBelakangLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbBelakang, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                .addContainerGap())
        );
        pBelakangLayout.setVerticalGroup(
            pBelakangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pBelakangLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbBelakang, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                .addContainerGap())
        );

        pCover.add(pBelakang);

        pDetailBuku.add(pCover);
        pCover.setBounds(6, 0, 150, 371);

        pDetail.setBackground(new java.awt.Color(255, 255, 255));
        pDetail.setLayout(new java.awt.BorderLayout());

        lbJudul.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbJudul.setForeground(new java.awt.Color(51, 51, 51));
        lbJudul.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbJudul.setText("Judul Buku");
        lbJudul.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        pDetail.add(lbJudul, java.awt.BorderLayout.PAGE_START);

        jPanel8.setBackground(new java.awt.Color(153, 153, 255));

        lbPenulis.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbPenulis.setText("Nama Penulis");

        lbPenerbit.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbPenerbit.setText("Nama Penerbit");

        lbTerbit.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbTerbit.setText("Tahun Terbit");

        lbHalaman.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbHalaman.setText("Jumlah Halaman");

        tfPenulis.setEditable(false);
        tfPenulis.setBackground(new java.awt.Color(255, 255, 255));

        tfPenerbit.setEditable(false);
        tfPenerbit.setBackground(new java.awt.Color(255, 255, 255));

        tfTahun.setEditable(false);
        tfTahun.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbPenulis)
                    .addComponent(lbPenerbit, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbTerbit)
                    .addComponent(lbHalaman))
                .addGap(27, 27, 27)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tfPenulis)
                    .addComponent(tfPenerbit)
                    .addComponent(tfTahun)
                    .addComponent(tfHalaman, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbPenulis)
                    .addComponent(tfPenulis, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbPenerbit)
                    .addComponent(tfPenerbit, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbTerbit)
                    .addComponent(tfTahun, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbHalaman)
                    .addComponent(tfHalaman, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(66, 66, 66))
        );

        pDetail.add(jPanel8, java.awt.BorderLayout.CENTER);

        pDetailBuku.add(pDetail);
        pDetail.setBounds(160, 0, 350, 371);

        getContentPane().add(pDetailBuku);
        pDetailBuku.setBounds(158, 96, 510, 370);

        pJudul.setBackground(new java.awt.Color(102, 102, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("PERPUSTAKAAN");

        javax.swing.GroupLayout pJudulLayout = new javax.swing.GroupLayout(pJudul);
        pJudul.setLayout(pJudulLayout);
        pJudulLayout.setHorizontalGroup(
            pJudulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pJudulLayout.createSequentialGroup()
                .addGap(142, 142, 142)
                .addComponent(jLabel1)
                .addContainerGap(153, Short.MAX_VALUE))
        );
        pJudulLayout.setVerticalGroup(
            pJudulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pJudulLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addContainerGap(388, Short.MAX_VALUE))
        );

        getContentPane().add(pJudul);
        pJudul.setBounds(0, 0, 670, 466);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btJurusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btJurusActionPerformed
        setImage("d19Jurus.jpg", lbDepan, 138, 173);
        setImage("b19Jurus.jpg", lbBelakang, 138, 173);
        lbJudul.setText("19 Jurus Mabuk");
        tfPenulis.setText("Nikko");
        tfPenerbit.setText("CENDOL");
        tfTahun.setText("1999");
        tfHalaman.setText("56");
    }//GEN-LAST:event_btJurusActionPerformed

    private void btSigarlakiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSigarlakiActionPerformed
        setImage("dSigarlaki.jpg", lbDepan, 138, 173);
        setImage("bSigarlaki.jpg", lbBelakang, 138, 173);
        lbJudul.setText("Sigarlaki dan Limbat");
        tfPenulis.setText("Denny Prabowo");
        tfPenerbit.setText("Kokogha");
        tfTahun.setText("2006");
        tfHalaman.setText("46");
    }//GEN-LAST:event_btSigarlakiActionPerformed

    private void btFabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFabelActionPerformed
        setImage("dAbc.jpg", lbDepan, 138, 173);
        setImage("bAbc.jpg", lbBelakang, 138, 173);
        lbJudul.setText("Fabel ABC");
        tfPenulis.setText("Yovita Siswati");
        tfPenerbit.setText("Megachan");
        tfTahun.setText("2012");
        tfHalaman.setText("40");
    }//GEN-LAST:event_btFabelActionPerformed

    private void btNinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNinaActionPerformed
        setImage("dNina.jpg", lbDepan, 138, 173);
        setImage("bNina.jpg", lbBelakang, 138, 173);
        lbJudul.setText("NinaBobo oh NinaBobo");
        tfPenulis.setText("Ayu Nastiti");
        tfPenerbit.setText("Wulandari");
        tfTahun.setText("1994");
        tfHalaman.setText("37");
    }//GEN-LAST:event_btNinaActionPerformed

    private void btBinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBinActionPerformed
        setImage("dBin.jpg", lbDepan, 138, 173);
        setImage("bBin.jpg", lbBelakang, 138, 173);
        lbJudul.setText("Bin & Tim Musikalnya");
        tfPenulis.setText("Arteen A");
        tfPenerbit.setText("Stella Ernes");
        tfTahun.setText("1985");
        tfHalaman.setText("21");
    }//GEN-LAST:event_btBinActionPerformed

    private void btTuhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTuhanActionPerformed
        setImage("dTuhan.jpg", lbDepan, 138, 173);
        setImage("bTuhan.jpg", lbBelakang, 138, 173);
        lbJudul.setText("Tuhan");
        tfPenulis.setText("NT Prasetyo");
        tfPenerbit.setText("Trifosa Lily Susanti");
        tfTahun.setText("2005");
        tfHalaman.setText("42");
    }//GEN-LAST:event_btTuhanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tugas3_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tugas3_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tugas3_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tugas3_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tugas3_1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBin;
    private javax.swing.JButton btFabel;
    private javax.swing.JButton btJurus;
    private javax.swing.JButton btNina;
    private javax.swing.JButton btSigarlaki;
    private javax.swing.JButton btTuhan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JLabel lbBelakang;
    private javax.swing.JLabel lbDaftar;
    private javax.swing.JLabel lbDepan;
    private javax.swing.JLabel lbHalaman;
    private javax.swing.JLabel lbJudul;
    private javax.swing.JLabel lbPenerbit;
    private javax.swing.JLabel lbPenulis;
    private javax.swing.JLabel lbTerbit;
    private javax.swing.JPanel pBelakang;
    private javax.swing.JPanel pCover;
    private javax.swing.JPanel pDaftar;
    private javax.swing.JPanel pDepan;
    private javax.swing.JPanel pDetail;
    private javax.swing.JPanel pDetailBuku;
    private javax.swing.JPanel pJudul;
    private javax.swing.JTextField tfHalaman;
    private javax.swing.JTextField tfPenerbit;
    private javax.swing.JTextField tfPenulis;
    private javax.swing.JTextField tfTahun;
    // End of variables declaration//GEN-END:variables
}
